const User = require('../models/User');
const Student = require('../models/Student');
const AuditLog = require('../models/AuditLog');

const seedInitialData = async () => {
  try {
    const existingUsers = await User.countDocuments();
    if (existingUsers > 0) {
      console.log('Database already has users, skipping seed.');
      return;
    }

    console.log('[System] Initializing demo users and academic profiles...');

    const adminUser = await User.create({
      name: 'SPS Super Administrator',
      email: 'admin@college.edu',
      password: 'Admin@123',
      role: 'SUPER_ADMIN',
      department: 'ALL',
    });

    await User.create({ name: 'Placement Coordinator', email: 'coordinator@college.edu', password: 'Coordinator@123', role: 'PLACEMENT_COORDINATOR', department: 'ALL' });
    await User.create({ name: 'Dr. K. S. Ramanathan (HOD)', email: 'hod@college.edu', password: 'Hod@123', role: 'HOD', department: 'CSE' });

    const facultyUser = await User.create({
      name: 'Prof. Priya Chandrasekar',
      email: 'faculty@college.edu',
      password: 'Mentor@123',
      role: 'FACULTY_MENTOR',
      department: 'CSE',
    });

    const studentsData = [
      // 1. High Performer - Placement Goal (Hosteller, 0 Arrears, Improving Trend)
      {
        personalDetails: {
          registerNumber: '710021104001',
          name: 'Aarav Sundaram',
          dob: '2003-05-14',
          gender: 'Male',
          department: 'CSE',
          section: 'A',
          institutionalEmail: 'aarav.s21@college.edu',
          personalEmail: 'aarav.tech2003@gmail.com',
          mobile: '9840123456',
          residentialAddress: 'No. 42, Anna Nagar West, Madurai, Tamil Nadu',
          category: 'Hosteller',
          hostelName: 'Kaveri Boys Hostel - Block B, Room 204',
          distanceFromCollege: 0,
        },
        familyDetails: {
          father: {
            name: 'Sundaram K',
            occupation: 'Civil Engineer (PWD)',
            incomeRange: '₹5–10 Lakhs',
            mobile: '9840198765',
          },
          mother: {
            name: 'Kavitha S',
            occupation: 'Government School Teacher',
            incomeRange: '₹3–5 Lakhs',
            mobile: '9840198764',
          },
          guardianName: '',
          emergencyContact: '9840198765',
          firstGenGraduate: 'No',
          scholarshipReceived: 'No',
          guidanceRequired: 'No',
        },
        semesters: [
          {
            semesterNumber: 1,
            sgpa: 8.5,
            cgpa: 8.5,
            attendance: 94,
            arrearStatus: 'No',
            numberOfArrears: 0,
            academicAchievements: 'Department 2nd rank in Sem 1',
            subjectsStrong: ['Python Programming', 'Engineering Physics'],
          },
          {
            semesterNumber: 2,
            sgpa: 8.8,
            cgpa: 8.65,
            attendance: 96,
            arrearStatus: 'No',
            numberOfArrears: 0,
            academicAchievements: 'Perfect score in Data Structures Lab',
            subjectsStrong: ['Data Structures', 'Digital Logic'],
          },
          {
            semesterNumber: 3,
            sgpa: 9.1,
            cgpa: 8.8,
            attendance: 92,
            arrearStatus: 'No',
            numberOfArrears: 0,
            academicAchievements: 'Class Topper in Sem 3',
            subjectsStrong: ['Object Oriented Programming', 'Database Systems'],
          },
          {
            semesterNumber: 4,
            sgpa: 9.3,
            cgpa: 8.92,
            attendance: 95,
            arrearStatus: 'No',
            numberOfArrears: 0,
            academicAchievements: '100% attendance award',
            subjectsStrong: ['Design and Analysis of Algorithms', 'Operating Systems'],
          },
        ],
        arrears: [],
        technicalProfile: {
          programmingLanguages: ['Java', 'Python', 'JavaScript', 'C++'],
          technicalSkills: ['React.js', 'Node.js', 'Express.js', 'MongoDB', 'Docker', 'Git'],
          preferredDomain: 'Web Development',
          areasOfInterest: ['Full Stack Architecture', 'Microservices', 'Distributed Systems'],
          certifications: [
            {
              name: 'AWS Certified Cloud Practitioner',
              issuingOrg: 'Amazon Web Services',
              completionDate: '2024-03-15',
              certificateLink: 'https://aws.amazon.com/verify/cert123',
            },
            {
              name: 'Meta Full-Stack Developer Professional Certificate',
              issuingOrg: 'Coursera / Meta',
              completionDate: '2023-11-20',
              certificateLink: 'https://coursera.org/verify/meta456',
            },
          ],
          projects: [
            {
              title: 'Campus Food Delivery & Pre-ordering Portal',
              description: 'MERN stack application allowing college students to pre-order food from college canteens with real-time token tracking.',
              technologies: ['React', 'Node.js', 'Express', 'MongoDB', 'Socket.io'],
              projectStatus: 'Completed',
              githubLink: 'https://github.com/aarav-s/campus-food-portal',
            },
            {
              title: 'Smart Library Resource Allocation Engine',
              description: 'Automated book reservation and seat allocation system with RFID tag integration simulation.',
              technologies: ['Java', 'Spring Boot', 'PostgreSQL'],
              projectStatus: 'In Progress',
              githubLink: 'https://github.com/aarav-s/smart-library',
            },
          ],
          hackathons: [
            {
              name: 'Smart India Hackathon 2023 (Internal College Round)',
              date: '2023-09-12',
              achievement: '1st Prize in Smart Automation Theme',
            },
          ],
          codingContests: [
            {
              name: 'LeetCode Weekly Contest 380',
              platform: 'LeetCode',
              result: 'Rank 1,420 / 25,000 (Top 6%)',
            },
          ],
          internships: [
            {
              company: 'Zoho Corporation',
              role: 'Software Development Engineering Intern',
              duration: '2 Months (Summer 2024)',
              description: 'Built REST API endpoints for Zoho CRM modules and improved query execution time by 18%.',
            },
          ],
          profileLinks: {
            github: 'https://github.com/aarav-sundaram-dev',
            linkedin: 'https://linkedin.com/in/aarav-sundaram',
            hackerrank: 'https://hackerrank.com/aarav_cse',
            hackerearth: 'https://hackerearth.com/@aarav_s',
          },
          communicationLevel: 'Excellent',
          aptitudeLevel: 'Excellent',
        },
        selfEvaluation: {
          academicStrengths: ['Consistent study schedule', 'Strong analytical understanding', 'Quick learner in algorithmic problem solving'],
          technicalStrengths: ['Full-stack MERN development', 'System Design fundamentals', 'Version control & Git best practices'],
          communicationStrengths: ['Comfortable presenting technical papers', 'Active team lead in projects'],
          leadershipQualities: ['Class Representative', 'Organized College Tech Symposium 2024'],
          teamworkAbilities: ['Conflict resolution in group projects', 'Peer programming mentor for juniors'],
          improvementAreas: ['Deep-dive into low-level OS kernel optimization', 'Public speaking in massive auditorium crowds'],
          subjectsNeedSupport: ['Computer Networks (Advanced Subnetting)'],
          techSkillsToDevelop: ['Kubernetes', 'Go Lang', 'GraphQL'],
          commSkillsToImprove: ['Executive briefing style communication'],
          aptitudeSkillsToImprove: ['High-speed quantitative shortcuts for competitive placement exams'],
          mentorSupportExpected: 'Guidance on high-package Tier-1 product placement preparation and mock technical interviews.',
          shortTermGoal: 'Secure a summer pre-placement offer (PPO) in a Tier-1 product company.',
          longTermGoal: 'Become a Principal Solutions Architect in a leading global tech enterprise.',
        },
        careerGoal: {
          primaryGoal: 'Placement',
          placement: {
            preferredRole: 'Software Development Engineer (SDE-1)',
            preferredDomain: 'Web Development',
            companyType: 'Product',
            expectedSalary: '₹14–18 LPA',
            preferredLocation: 'Bengaluru / Chennai / Hyderabad',
            targetCompanies: ['Google', 'Microsoft', 'Amazon', 'Zoho', 'Thoughtworks'],
            trainingSupport: 'Advanced Data Structures & Algorithms mock rounds, System Design discussions.',
            skillsToImprove: ['System Design', 'Scalability Patterns'],
          },
        },
        mentorInterventions: [
          {
            date: new Date('2024-02-10'),
            reason: 'Routine Semester Review & Placement Roadmap',
            mentorNote: 'Student is performing exceptionally well. Recommended applying for Google Summer of Code and Tier-1 off-campus internships.',
            actionTaken: 'Shared DSA mock problem set and reviewed resume.',
            followUpDate: new Date('2024-08-15'),
            status: 'Resolved',
            mentorName: 'Prof. Priya Chandrasekar',
            mentorId: facultyUser._id,
          },
        ],
        consent: true,
      },

      // 2. Student Requiring Attention - Active Arrear & Low Attendance (Day Scholar)
      {
        personalDetails: {
          registerNumber: '710021104018',
          name: 'Dinesh Karthik M',
          dob: '2003-08-22',
          gender: 'Male',
          department: 'CSE',
          section: 'B',
          institutionalEmail: 'dinesh.k21@college.edu',
          personalEmail: 'dineshkarthik2003@yahoo.com',
          mobile: '9790112233',
          residentialAddress: 'Plot 15, Vandalur Road, Tambaram, Chennai',
          category: 'Day Scholar',
          hostelName: '',
          distanceFromCollege: 28,
        },
        familyDetails: {
          father: {
            name: 'Murugesan P',
            occupation: 'Auto Driver',
            incomeRange: 'Below ₹1 Lakh',
            mobile: '9790112234',
          },
          mother: {
            name: 'Selvi M',
            occupation: 'Homemaker',
            incomeRange: 'Below ₹1 Lakh',
            mobile: '9790112235',
          },
          guardianName: '',
          emergencyContact: '9790112234',
          firstGenGraduate: 'Yes',
          scholarshipReceived: 'Yes',
          guidanceRequired: 'Yes',
        },
        semesters: [
          {
            semesterNumber: 1,
            sgpa: 6.8,
            cgpa: 6.8,
            attendance: 82,
            arrearStatus: 'No',
            numberOfArrears: 0,
            academicAchievements: '',
            subjectsStrong: ['Engineering Chemistry'],
          },
          {
            semesterNumber: 2,
            sgpa: 5.9,
            cgpa: 6.35,
            attendance: 72,
            arrearStatus: 'Yes',
            numberOfArrears: 1,
            academicAchievements: '',
            subjectsStrong: ['Programming in C'],
          },
          {
            semesterNumber: 3,
            sgpa: 5.4,
            cgpa: 6.03,
            attendance: 68,
            arrearStatus: 'Yes',
            numberOfArrears: 2,
            academicAchievements: '',
            subjectsStrong: [],
          },
        ],
        arrears: [
          {
            semesterOccurred: 2,
            subjectCode: 'MA8251',
            subjectName: 'Engineering Mathematics II',
            attempts: 2,
            status: 'Pending',
            clearedSemester: null,
            clearedGrade: '',
            reason: 'Struggled with Differential Equations and Vector Calculus concepts; long commute caused frequent tiredness.',
            remedialRequired: 'Yes',
            mentorSupportRequired: 'Yes',
          },
          {
            semesterOccurred: 3,
            subjectCode: 'CS8391',
            subjectName: 'Data Structures',
            attempts: 1,
            status: 'Pending',
            clearedSemester: null,
            clearedGrade: '',
            reason: 'Difficulty in implementing balanced trees and dynamic memory allocation pointers.',
            remedialRequired: 'Yes',
            mentorSupportRequired: 'Yes',
          },
        ],
        technicalProfile: {
          programmingLanguages: ['C', 'Java (Basics)'],
          technicalSkills: ['HTML', 'CSS'],
          preferredDomain: 'Software Development',
          areasOfInterest: ['Application Development'],
          certifications: [],
          projects: [],
          hackathons: [],
          codingContests: [],
          internships: [],
          profileLinks: {
            github: '',
            linkedin: 'https://linkedin.com/in/dinesh-karthik-m',
            hackerrank: '',
            hackerearth: '',
          },
          communicationLevel: 'Beginner',
          aptitudeLevel: 'Beginner',
        },
        selfEvaluation: {
          academicStrengths: ['Hardworking when concepts are explained patiently in Tamil/English mix'],
          technicalStrengths: ['Good understanding of basic C looping and arrays'],
          communicationStrengths: ['Humble, polite listener'],
          leadershipQualities: [],
          teamworkAbilities: ['Willing to take up supporting roles in laboratory experiments'],
          improvementAreas: ['Mathematics fundamentals', 'Data Structures coding', 'English communication in viva'],
          subjectsNeedSupport: ['MA8251 Engineering Mathematics II', 'CS8391 Data Structures'],
          techSkillsToDevelop: ['Java', 'SQL Database'],
          commSkillsToImprove: ['Technical vocabulary', 'Speaking with confidence during interviews'],
          aptitudeSkillsToImprove: ['Basic mental math and aptitude problem solving'],
          mentorSupportExpected: 'Requesting remedial tutoring for Maths II and Data Structures; also guidance on travel concessions or hostel accommodation.',
          shortTermGoal: 'Clear both pending arrears in the upcoming semester exams and achieve 75%+ attendance.',
          longTermGoal: 'Get placed in an IT services company to support my family financially.',
        },
        careerGoal: {
          primaryGoal: 'Placement',
          placement: {
            preferredRole: 'Junior Software Engineer / Trainee',
            preferredDomain: 'Software Development',
            companyType: 'Service',
            expectedSalary: '₹3.5–5 LPA',
            preferredLocation: 'Chennai',
            targetCompanies: ['TCS', 'Infosys', 'Wipro', 'Cognizant'],
            trainingSupport: 'Remedial training in aptitude, foundation Java training, and Maths coaching.',
            skillsToImprove: ['Java', 'Data Structures', 'Quantitative Aptitude'],
          },
        },
        mentorInterventions: [
          {
            date: new Date('2024-03-05'),
            reason: 'Attendance below 75% & 2 Pending Arrears',
            mentorNote: 'Met with Dinesh. Student lives 28km away and travels 2.5 hours each way by bus, leading to severe fatigue and morning absenteeism. Counseled him on time management and referred to student welfare officer for subsidized hostel accommodation.',
            actionTaken: 'Arranged peer tutoring for Engineering Mathematics II with senior student mentor.',
            followUpDate: new Date('2024-04-10'),
            status: 'In Progress',
            mentorName: 'Prof. Priya Chandrasekar',
            mentorId: facultyUser._id,
          },
        ],
        consent: true,
      },

      // 3. Higher Studies Goal - Turnaround Student (Cleared Arrear, Improving Trend)
      {
        personalDetails: {
          registerNumber: '710021104035',
          name: 'Meera Venkatakrishnan',
          dob: '2003-11-09',
          gender: 'Female',
          department: 'CSE',
          section: 'A',
          institutionalEmail: 'meera.v21@college.edu',
          personalEmail: 'meera.venkat.research@gmail.com',
          mobile: '9841223344',
          residentialAddress: 'Flat 3B, Sunshine Apartments, Velachery, Chennai',
          category: 'Day Scholar',
          hostelName: '',
          distanceFromCollege: 14,
        },
        familyDetails: {
          father: {
            name: 'Venkatakrishnan R',
            occupation: 'Chartered Accountant',
            incomeRange: 'Above ₹10 Lakhs',
            mobile: '9841223340',
          },
          mother: {
            name: 'Sujatha V',
            occupation: 'Bank Manager',
            incomeRange: '₹5–10 Lakhs',
            mobile: '9841223341',
          },
          guardianName: '',
          emergencyContact: '9841223340',
          firstGenGraduate: 'No',
          scholarshipReceived: 'No',
          guidanceRequired: 'No',
        },
        semesters: [
          {
            semesterNumber: 1,
            sgpa: 7.2,
            cgpa: 7.2,
            attendance: 88,
            arrearStatus: 'No',
            numberOfArrears: 0,
            academicAchievements: '',
            subjectsStrong: ['Problem Solving with Python'],
          },
          {
            semesterNumber: 2,
            sgpa: 6.9,
            cgpa: 7.05,
            attendance: 84,
            arrearStatus: 'Yes',
            numberOfArrears: 1,
            academicAchievements: '',
            subjectsStrong: ['Technical English'],
          },
          {
            semesterNumber: 3,
            sgpa: 8.4,
            cgpa: 7.5,
            attendance: 91,
            arrearStatus: 'No',
            numberOfArrears: 0,
            academicAchievements: 'Cleared arrear with A grade, achieved Dean List recognition in Sem 3',
            subjectsStrong: ['Database Management Systems', 'Object Oriented Programming'],
          },
          {
            semesterNumber: 4,
            sgpa: 8.9,
            cgpa: 7.85,
            attendance: 93,
            arrearStatus: 'No',
            numberOfArrears: 0,
            academicAchievements: 'Best Paper Presentation at National Student Research Colloquium',
            subjectsStrong: ['Artificial Intelligence', 'Theory of Computation'],
          },
        ],
        arrears: [
          {
            semesterOccurred: 2,
            subjectCode: 'EC8251',
            subjectName: 'Electronic Devices and Circuits',
            attempts: 2,
            status: 'Cleared',
            clearedSemester: 3,
            clearedGrade: 'A',
            reason: 'Health issues during Sem 2 examinations (diagnosed with typhoid right before EDC exam).',
            remedialRequired: 'No',
            mentorSupportRequired: 'Yes',
          },
        ],
        technicalProfile: {
          programmingLanguages: ['Python', 'R', 'C++', 'SQL'],
          technicalSkills: ['PyTorch', 'Scikit-Learn', 'Natural Language Processing', 'Data Analysis', 'LaTeX'],
          preferredDomain: 'AI/ML',
          areasOfInterest: ['Natural Language Processing', 'Large Language Models', 'Computer Vision in Healthcare'],
          certifications: [
            {
              name: 'Deep Learning Specialization',
              issuingOrg: 'DeepLearning.AI / Coursera',
              completionDate: '2023-12-10',
              certificateLink: 'https://coursera.org/verify/dl-meera',
            },
          ],
          projects: [
            {
              title: 'Clinical Named Entity Recognition from EHR Records',
              description: 'Fine-tuned BioBERT model to extract medical symptoms and dosages from unstructured clinical notes.',
              technologies: ['Python', 'PyTorch', 'HuggingFace Transformers', 'BioBERT'],
              projectStatus: 'Completed',
              githubLink: 'https://github.com/meera-v/clinical-ner-ehr',
            },
          ],
          hackathons: [
            {
              name: 'HealthTech AI Hackathon 2024',
              date: '2024-01-20',
              achievement: 'Runner Up - Cash prize ₹25,000',
            },
          ],
          codingContests: [],
          internships: [
            {
              company: 'IIT Madras Research Park (Healthcare AI Lab)',
              role: 'Undergraduate Student Research Fellow',
              duration: '3 Months (Dec 2023 - Feb 2024)',
              description: 'Worked on automated screening of diabetic retinopathy fundus images using deep convolutional networks.',
            },
          ],
          profileLinks: {
            github: 'https://github.com/meera-v-research',
            linkedin: 'https://linkedin.com/in/meera-venkat-ai',
            hackerrank: 'https://hackerrank.com/meera_ai',
            hackerearth: '',
          },
          communicationLevel: 'Excellent',
          aptitudeLevel: 'Advanced',
        },
        selfEvaluation: {
          academicStrengths: ['Strong conceptual grasp of machine learning mathematical formulations', 'Disciplined academic writing'],
          technicalStrengths: ['Python PyTorch development', 'Literature survey and paper publication'],
          communicationStrengths: ['Clear academic writing', 'Confident seminar presentations'],
          leadershipQualities: ['Student Chair of IEEE Computer Society Student Branch'],
          teamworkAbilities: ['Coordinates research group papers seamlessly'],
          improvementAreas: ['Standardized test time management (GRE Quant section)'],
          subjectsNeedSupport: [],
          techSkillsToDevelop: ['Distributed Training (DeepSpeed)', 'MLOps'],
          commSkillsToImprove: ['IELTS Speaking Band 8+ prep'],
          aptitudeSkillsToImprove: ['GRE quantitative reasoning rapid shortcuts'],
          mentorSupportExpected: 'Letters of Recommendation (LORs) and guidance on reviewing Statement of Purpose (SOP) for US/German MS applications.',
          shortTermGoal: 'Score 325+ in GRE and 8.0 in IELTS by August 2024.',
          longTermGoal: 'Complete M.S. in Computer Science at a top global university and pursue a Ph.D. in Generative AI.',
        },
        careerGoal: {
          primaryGoal: 'Higher Studies',
          higherStudies: {
            preferredProgramme: 'Master of Science (MS)',
            specialization: 'Artificial Intelligence & Machine Learning',
            preferredCountry: 'United States / Germany',
            targetInstitutions: ['Carnegie Mellon University (CMU)', 'Georgia Tech', 'TU Munich', 'IIT Madras (M.S. by Research)'],
            plannedExams: ['GRE', 'IELTS', 'TOEFL'],
            admissionYear: 2025,
            guidanceRequired: 'Guidance on choosing faculty research advisors, shortlisting universities, and drafting research proposals.',
          },
        },
        mentorInterventions: [
          {
            date: new Date('2023-09-18'),
            reason: 'Medical Leave Support & Arrear Clearing Plan',
            mentorNote: 'Student contracted typhoid during Sem 2 exams. Reassured student and assisted with academic medical leave documentation so she could reappear in Sem 3.',
            actionTaken: 'Facilitated re-exam schedule and mentor check-ins.',
            followUpDate: new Date('2023-12-05'),
            status: 'Resolved',
            mentorName: 'Prof. Priya Chandrasekar',
            mentorId: facultyUser._id,
          },
        ],
        consent: true,
      },

      // 4. Entrepreneurship Goal - Hardware & IoT Innovation (Hosteller)
      {
        personalDetails: {
          registerNumber: '710021104049',
          name: 'Rohit Balaji S',
          dob: '2003-03-30',
          gender: 'Male',
          department: 'ECE',
          section: 'A',
          institutionalEmail: 'rohit.b21@college.edu',
          personalEmail: 'rohit.balaji.innovator@gmail.com',
          mobile: '9840334455',
          residentialAddress: 'No. 18, Gandhi Road, Tiruchirappalli, Tamil Nadu',
          category: 'Hosteller',
          hostelName: 'Bhavani Boys Hostel - Room 108',
          distanceFromCollege: 0,
        },
        familyDetails: {
          father: {
            name: 'Balaji S',
            occupation: 'Small Business Owner (Electrical Supplies)',
            incomeRange: '₹3–5 Lakhs',
            mobile: '9840334450',
          },
          mother: {
            name: 'Gayathri B',
            occupation: 'Homemaker',
            incomeRange: 'Below ₹1 Lakh',
            mobile: '9840334451',
          },
          guardianName: '',
          emergencyContact: '9840334450',
          firstGenGraduate: 'Yes',
          scholarshipReceived: 'No',
          guidanceRequired: 'Yes',
        },
        semesters: [
          {
            semesterNumber: 1,
            sgpa: 7.6,
            cgpa: 7.6,
            attendance: 90,
            arrearStatus: 'No',
            numberOfArrears: 0,
            academicAchievements: '',
            subjectsStrong: ['Circuit Theory', 'Basic Electrical Engineering'],
          },
          {
            semesterNumber: 2,
            sgpa: 7.8,
            cgpa: 7.7,
            attendance: 88,
            arrearStatus: 'No',
            numberOfArrears: 0,
            academicAchievements: 'Winner of College Innovation Challenge',
            subjectsStrong: ['Microprocessors and Microcontrollers'],
          },
          {
            semesterNumber: 3,
            sgpa: 8.0,
            cgpa: 7.8,
            attendance: 89,
            arrearStatus: 'No',
            numberOfArrears: 0,
            academicAchievements: 'College Incubation Center Seed Grant Selection',
            subjectsStrong: ['Embedded Systems', 'Signals and Systems'],
          },
        ],
        arrears: [],
        technicalProfile: {
          programmingLanguages: ['Embedded C', 'Python', 'C++'],
          technicalSkills: ['ESP32', 'Arduino', 'PCB Design (KiCAD)', 'MQTT Protocol', 'AWS IoT Core'],
          preferredDomain: 'Other',
          areasOfInterest: ['Internet of Things', 'Agritech Hardware', 'Edge Computing'],
          certifications: [
            {
              name: 'Architecting Smart IoT Devices',
              issuingOrg: 'Coursera / UC San Diego',
              completionDate: '2023-10-15',
              certificateLink: 'https://coursera.org/verify/iot-rohit',
            },
          ],
          projects: [
            {
              title: 'AgroSense: Solar-Powered IoT Soil Moisture & Nitrogen Telemetry',
              description: 'Low-cost solar telemetry probe that transmits real-time nitrogen and soil moisture metrics to farmer smartphones over LoRaWAN.',
              technologies: ['ESP32', 'LoRaWAN', 'Embedded C', 'KiCAD', 'Flutter'],
              projectStatus: 'Completed',
              githubLink: 'https://github.com/rohit-b/agrosense-iot',
            },
          ],
          hackathons: [
            {
              name: 'Tamil Nadu Startup Thiruvizha 2023',
              date: '2023-10-28',
              achievement: 'Top 10 Finalist in Agritech Category',
            },
          ],
          codingContests: [],
          internships: [
            {
              company: 'AgriTech NextGen Solutions',
              role: 'Hardware Firmware Engineering Intern',
              duration: '2 Months (May - July 2023)',
              description: 'Designed custom 2-layer PCB for agricultural sensor node with ultra-low sleep current consumption.',
            },
          ],
          profileLinks: {
            github: 'https://github.com/rohit-balaji-hardware',
            linkedin: 'https://linkedin.com/in/rohit-balaji-iot',
            hackerrank: '',
            hackerearth: '',
          },
          communicationLevel: 'Advanced',
          aptitudeLevel: 'Intermediate',
        },
        selfEvaluation: {
          academicStrengths: ['Practical laboratory excellence', 'Hands-on electronic circuit prototyping'],
          technicalStrengths: ['PCB design & rapid 3D prototyping', 'Firmware debugging with logic analyzers'],
          communicationStrengths: ['Enthusiastic pitch presentations to investors and juries'],
          leadershipQualities: ['Founder & Team Lead for startup project', 'Mentors junior robotics club'],
          teamworkAbilities: ['Cross-functional team coordination with agriculture students'],
          improvementAreas: ['Balance time between startup prototypes and theoretical semester exams'],
          subjectsNeedSupport: ['Electromagnetic Fields (Theoretical derivations)'],
          techSkillsToDevelop: ['Edge AI / TinyML', 'Bluetooth Mesh'],
          commSkillsToImprove: ['Investor financial pitching and equity term sheet negotiations'],
          aptitudeSkillsToImprove: ['Financial accounting and startup cash flow projections'],
          mentorSupportExpected: 'Guidance on patent filing, access to college maker space 3D printers, and college incubation seed funding assistance.',
          shortTermGoal: 'Deploy 50 beta test units of AgroSense with farmers in Thanjavur district.',
          longTermGoal: 'Incorporate an Agritech startup and raise Seed funding under Startup India Seed Fund Scheme (SISFS).',
        },
        careerGoal: {
          primaryGoal: 'Entrepreneurship',
          entrepreneurship: {
            startupIdea: 'AgroSense Technologies: Precision Irrigation & Fertilizer IoT Probes for Smallholder Farmers',
            problemAddressed: 'Over-irrigation and excessive chemical fertilizer runoff that degrades topsoil and wastes water in semi-arid zones.',
            proposedSolution: 'Sub-$25 solar powered IoT probe transmitting hyper-local soil moisture and nutrient metrics directly via SMS/WhatsApp without needing internet.',
            targetCustomers: 'Small and medium crop farmers, organic farming collectives, greenhouse operators.',
            currentStage: 'Prototype',
            teamDetails: '3 students: 1 Hardware Engineer (Rohit), 1 Software Backend, 1 Agriculture Science advisor.',
            techSupport: 'Access to college high-frequency RF test bench and Maker Space CNC milling.',
            fundingSupport: 'Applying for ₹5 Lakhs grant under EDII-TN IVP (Innovation Voucher Programme).',
            incubationSupport: 'Mentorship on Intellectual Property (patent search) and Company Incorporation (CIN/Pvt Ltd).',
            expectedLaunchYear: 2025,
          },
        },
        mentorInterventions: [
          {
            date: new Date('2024-01-15'),
            reason: 'Incubation Grant Application Endorsement',
            mentorNote: 'Reviewed Rohit AgroSense pitch deck and patent draft. Endorsed the student application for college incubation seed funding.',
            actionTaken: 'Connected student with College Dean of Research & Incubation Director.',
            followUpDate: new Date('2024-06-20'),
            status: 'Resolved',
            mentorName: 'Prof. Priya Chandrasekar',
            mentorId: facultyUser._id,
          },
        ],
        consent: true,
      },

      // 5. IT Department - Placement (Product Company, High CGPA, Stable Trend)
      {
        personalDetails: {
          registerNumber: '710021205008',
          name: 'Siddharth Rangarajan',
          dob: '2003-07-19',
          gender: 'Male',
          department: 'IT',
          section: 'A',
          institutionalEmail: 'siddharth.r21@college.edu',
          personalEmail: 'sid.rangarajan2003@gmail.com',
          mobile: '9840445566',
          residentialAddress: 'No. 8, 4th Main Road, Besant Nagar, Chennai',
          category: 'Day Scholar',
          hostelName: '',
          distanceFromCollege: 18,
        },
        familyDetails: {
          father: {
            name: 'Rangarajan S',
            occupation: 'Senior IT Consultant',
            incomeRange: 'Above ₹10 Lakhs',
            mobile: '9840445560',
          },
          mother: {
            name: 'Anuradha R',
            occupation: 'Professor of Economics',
            incomeRange: '₹5–10 Lakhs',
            mobile: '9840445561',
          },
          guardianName: '',
          emergencyContact: '9840445560',
          firstGenGraduate: 'No',
          scholarshipReceived: 'No',
          guidanceRequired: 'No',
        },
        semesters: [
          {
            semesterNumber: 1,
            sgpa: 8.7,
            cgpa: 8.7,
            attendance: 92,
            arrearStatus: 'No',
            numberOfArrears: 0,
            academicAchievements: 'Department topper in Information Technology',
            subjectsStrong: ['C Programming', 'Discrete Mathematics'],
          },
          {
            semesterNumber: 2,
            sgpa: 8.8,
            cgpa: 8.75,
            attendance: 90,
            arrearStatus: 'No',
            numberOfArrears: 0,
            academicAchievements: '',
            subjectsStrong: ['Data Structures and Algorithms'],
          },
          {
            semesterNumber: 3,
            sgpa: 8.8,
            cgpa: 8.77,
            attendance: 94,
            arrearStatus: 'No',
            numberOfArrears: 0,
            academicAchievements: 'Dean List Honoree',
            subjectsStrong: ['Web Technology', 'Computer Architecture'],
          },
        ],
        arrears: [],
        technicalProfile: {
          programmingLanguages: ['Go', 'JavaScript', 'Python', 'C++'],
          technicalSkills: ['Docker', 'Kubernetes', 'Cloud Native', 'PostgreSQL', 'Redis', 'Kafka'],
          preferredDomain: 'Cloud Computing',
          areasOfInterest: ['Site Reliability Engineering', 'Cloud Native Systems', 'Distributed Databases'],
          certifications: [
            {
              name: 'Certified Kubernetes Application Developer (CKAD)',
              issuingOrg: 'Linux Foundation / CNCF',
              completionDate: '2024-02-18',
              certificateLink: 'https://cncf.lfx.dev/verify/ckad-sid',
            },
          ],
          projects: [
            {
              title: 'KubeWatchdog: Lightweight Kubernetes Pod Metrics Daemon',
              description: 'Golang daemon tracking memory leaks and CPU throttle spikes with automated Slack webhook notifications.',
              technologies: ['Go', 'Kubernetes API', 'Prometheus', 'Docker'],
              projectStatus: 'Completed',
              githubLink: 'https://github.com/sid-rang/kubewatchdog',
            },
          ],
          hackathons: [],
          codingContests: [
            {
              name: 'Google Hash Code 2023',
              platform: 'Google Coding Competitions',
              result: 'National Rank 84',
            },
          ],
          internships: [
            {
              company: 'Freshworks Inc.',
              role: 'Cloud Operations Intern',
              duration: '2 Months (May - June 2024)',
              description: 'Automated AWS infrastructure provisioning using Terraform and configured Prometheus monitoring dashboards.',
            },
          ],
          profileLinks: {
            github: 'https://github.com/sid-rang-cloud',
            linkedin: 'https://linkedin.com/in/siddharth-rangarajan-cloud',
            hackerrank: 'https://hackerrank.com/sid_cloud',
            hackerearth: '',
          },
          communicationLevel: 'Excellent',
          aptitudeLevel: 'Excellent',
        },
        selfEvaluation: {
          academicStrengths: ['Deep theoretical understanding of operating systems and virtualization'],
          technicalStrengths: ['Golang concurrency patterns', 'Kubernetes container orchestration'],
          communicationStrengths: ['Technical writing and documentation'],
          leadershipQualities: ['Open-source repository maintainer'],
          teamworkAbilities: ['Cross-functional team collaborator'],
          improvementAreas: ['Frontend UI design aesthetics (prefers backend/infrastructure)'],
          subjectsNeedSupport: [],
          techSkillsToDevelop: ['Terraform Advanced', 'eBPF'],
          commSkillsToImprove: ['Executive presentation and negotiation'],
          aptitudeSkillsToImprove: ['Rapid logical puzzles'],
          mentorSupportExpected: 'Guidance on top-tier cloud architecture placement interviews.',
          shortTermGoal: 'Secure Cloud SRE role with >15 LPA package.',
          longTermGoal: 'Principal Infrastructure Engineer in a global tech firm.',
        },
        careerGoal: {
          primaryGoal: 'Placement',
          placement: {
            preferredRole: 'Site Reliability Engineer / Cloud Backend Engineer',
            preferredDomain: 'Cloud Computing',
            companyType: 'Product',
            expectedSalary: '₹16–22 LPA',
            preferredLocation: 'Bengaluru / Hyderabad',
            targetCompanies: ['Google Cloud', 'Microsoft Azure', 'Atlassian', 'Freshworks', 'Salesforce'],
            trainingSupport: 'Advanced System Design mock rounds.',
            skillsToImprove: ['System Design', 'Distributed Systems'],
          },
        },
        mentorInterventions: [],
        consent: true,
      },

      // 6. AIDS Department - Higher Studies (Declining Trend Warning, Day Scholar)
      {
        personalDetails: {
          registerNumber: '710021243012',
          name: 'Ananya Ramesh',
          dob: '2003-10-04',
          gender: 'Female',
          department: 'AIDS',
          section: 'A',
          institutionalEmail: 'ananya.r21@college.edu',
          personalEmail: 'ananya.ramesh.ds@gmail.com',
          mobile: '9840556677',
          residentialAddress: 'No. 33, 1st Cross Street, T. Nagar, Chennai',
          category: 'Day Scholar',
          hostelName: '',
          distanceFromCollege: 12,
        },
        familyDetails: {
          father: {
            name: 'Ramesh N',
            occupation: 'Auditor',
            incomeRange: '₹5–10 Lakhs',
            mobile: '9840556670',
          },
          mother: {
            name: 'Meenakshi R',
            occupation: 'High School Mathematics Teacher',
            incomeRange: '₹3–5 Lakhs',
            mobile: '9840556671',
          },
          guardianName: '',
          emergencyContact: '9840556670',
          firstGenGraduate: 'No',
          scholarshipReceived: 'No',
          guidanceRequired: 'No',
        },
        semesters: [
          {
            semesterNumber: 1,
            sgpa: 8.6,
            cgpa: 8.6,
            attendance: 92,
            arrearStatus: 'No',
            numberOfArrears: 0,
            academicAchievements: 'Department Academic Excellence award',
            subjectsStrong: ['Foundations of Data Science', 'Linear Algebra'],
          },
          {
            semesterNumber: 2,
            sgpa: 8.0,
            cgpa: 8.3,
            attendance: 84,
            arrearStatus: 'No',
            numberOfArrears: 0,
            academicAchievements: '',
            subjectsStrong: ['Python for Data Analysis'],
          },
          {
            semesterNumber: 3,
            sgpa: 7.3,
            cgpa: 7.97,
            attendance: 78,
            arrearStatus: 'No',
            numberOfArrears: 0,
            academicAchievements: '',
            subjectsStrong: ['Data Visualization'],
          },
        ],
        arrears: [],
        technicalProfile: {
          programmingLanguages: ['Python', 'R', 'SQL'],
          technicalSkills: ['Pandas', 'NumPy', 'Tableau', 'Scikit-Learn', 'Matplotlib'],
          preferredDomain: 'Data Science',
          areasOfInterest: ['Data Analytics', 'Health Informatics', 'Business Intelligence'],
          certifications: [
            {
              name: 'Google Data Analytics Professional Certificate',
              issuingOrg: 'Coursera / Google',
              completionDate: '2023-08-12',
              certificateLink: 'https://coursera.org/verify/google-data-ananya',
            },
          ],
          projects: [
            {
              title: 'Urban Public Transit Passenger Density Forecaster',
              description: 'Time series forecasting model predicting peak bus ridership on Chennai MTC corridors.',
              technologies: ['Python', 'SARIMA', 'Pandas', 'Streamlit'],
              projectStatus: 'Completed',
              githubLink: 'https://github.com/ananya-r/transit-forecaster',
            },
          ],
          hackathons: [],
          codingContests: [],
          internships: [],
          profileLinks: {
            github: 'https://github.com/ananya-ramesh-ds',
            linkedin: 'https://linkedin.com/in/ananya-ramesh-data',
            hackerrank: 'https://hackerrank.com/ananya_ds',
            hackerearth: '',
          },
          communicationLevel: 'Advanced',
          aptitudeLevel: 'Intermediate',
        },
        selfEvaluation: {
          academicStrengths: ['Quick grasp of statistical distributions and data visualization'],
          technicalStrengths: ['Python Pandas & SQL querying'],
          communicationStrengths: ['Presenting data dashboards to non-technical audiences'],
          leadershipQualities: ['Data Science Club secretary'],
          teamworkAbilities: ['Active team player in hackathons'],
          improvementAreas: ['Drop in SGPA over last 2 semesters due to personal health and exam anxiety'],
          subjectsNeedSupport: ['Optimization Techniques in Data Science'],
          techSkillsToDevelop: ['PySpark', 'Deep Learning'],
          commSkillsToImprove: ['High pressure viva interviews'],
          aptitudeSkillsToImprove: ['Quantitative aptitude speed'],
          mentorSupportExpected: 'Academic counseling to stabilize declining SGPA trend and GRE planning.',
          shortTermGoal: 'Recover SGPA back to 8.5+ in Semester 4.',
          longTermGoal: 'Pursue Master in Business Analytics (MSBA) in the US or UK.',
        },
        careerGoal: {
          primaryGoal: 'Higher Studies',
          higherStudies: {
            preferredProgramme: 'Master of Science in Business Analytics (MSBA)',
            specialization: 'Business Analytics & Decision Sciences',
            preferredCountry: 'United States / Singapore',
            targetInstitutions: ['Columbia University', 'NUS Singapore', 'UT Austin McCombs'],
            plannedExams: ['GRE', 'TOEFL'],
            admissionYear: 2025,
            guidanceRequired: 'Advice on SOP drafting and course prerequisites for MSBA programs.',
          },
        },
        mentorInterventions: [
          {
            date: new Date('2024-02-28'),
            reason: 'Declining academic trend (-0.7 SGPA drop in Sem 3)',
            mentorNote: 'Met with Ananya to analyze reason behind drop from 8.6 to 7.3. Student had difficulty balancing club activities with intense theory courses. Devised a revised weekly study timetable.',
            actionTaken: 'Weekly progress check-in schedule established.',
            followUpDate: new Date('2024-04-30'),
            status: 'In Progress',
            mentorName: 'Prof. Priya Chandrasekar',
            mentorId: facultyUser._id,
          },
        ],
        consent: true,
      },

      // 7. Mechanical Engineering - Placement (Core / Automotive Domain, Hosteller)
      {
        personalDetails: {
          registerNumber: '710021114022',
          name: 'Vigneshwaran K',
          dob: '2003-06-11',
          gender: 'Male',
          department: 'MECH',
          section: 'A',
          institutionalEmail: 'vignesh.k21@college.edu',
          personalEmail: 'vicky.mech2003@gmail.com',
          mobile: '9840667788',
          residentialAddress: 'No. 55, South Car Street, Chidambaram, Tamil Nadu',
          category: 'Hosteller',
          hostelName: 'Kaveri Boys Hostel - Block A, Room 102',
          distanceFromCollege: 0,
        },
        familyDetails: {
          father: {
            name: 'Kandasamy M',
            occupation: 'Farmer',
            incomeRange: '₹1–3 Lakhs',
            mobile: '9840667780',
          },
          mother: {
            name: 'Pachaiammal K',
            occupation: 'Homemaker',
            incomeRange: 'Below ₹1 Lakh',
            mobile: '9840667781',
          },
          guardianName: '',
          emergencyContact: '9840667780',
          firstGenGraduate: 'Yes',
          scholarshipReceived: 'Yes',
          guidanceRequired: 'Yes',
        },
        semesters: [
          {
            semesterNumber: 1,
            sgpa: 7.8,
            cgpa: 7.8,
            attendance: 94,
            arrearStatus: 'No',
            numberOfArrears: 0,
            academicAchievements: '',
            subjectsStrong: ['Engineering Graphics', 'Workshop Practices'],
          },
          {
            semesterNumber: 2,
            sgpa: 8.1,
            cgpa: 7.95,
            attendance: 92,
            arrearStatus: 'No',
            numberOfArrears: 0,
            academicAchievements: '',
            subjectsStrong: ['Engineering Mechanics'],
          },
          {
            semesterNumber: 3,
            sgpa: 8.3,
            cgpa: 8.07,
            attendance: 95,
            arrearStatus: 'No',
            numberOfArrears: 0,
            academicAchievements: 'SAE BAJA chassis fabrication team lead',
            subjectsStrong: ['Thermodynamics', 'Fluid Mechanics and Machinery'],
          },
        ],
        arrears: [],
        technicalProfile: {
          programmingLanguages: ['Python (Basics)', 'MATLAB'],
          technicalSkills: ['SolidWorks', 'ANSYS Fluent', 'AutoCAD', 'GD&T', 'CNC Programming'],
          preferredDomain: 'Other',
          areasOfInterest: ['Automotive Powertrain', 'Electric Vehicle Battery Packaging', 'Computational Fluid Dynamics'],
          certifications: [
            {
              name: 'Certified SOLIDWORKS Associate in Mechanical Design (CSWA)',
              issuingOrg: 'Dassault Systèmes',
              completionDate: '2023-09-05',
              certificateLink: 'https://solidworks.virtualtester.com/verify/cswa-vicky',
            },
          ],
          projects: [
            {
              title: 'Design and FEA Analysis of Formula Student Impact Attenuator',
              description: 'Designed honeycomb composite crash box that absorbs 7300 Joules of kinetic energy meeting SAE standards.',
              technologies: ['SolidWorks', 'ANSYS Workbench', 'Non-linear FEA'],
              projectStatus: 'Completed',
              githubLink: '',
            },
          ],
          hackathons: [],
          codingContests: [],
          internships: [
            {
              company: 'Ashok Leyland Technical Centre',
              role: 'Chassis Design Trainee',
              duration: '1 Month (June 2023)',
              description: 'Assisted in finite element modeling of commercial truck suspension leaf springs.',
            },
          ],
          profileLinks: {
            github: '',
            linkedin: 'https://linkedin.com/in/vigneshwaran-mech',
            hackerrank: '',
            hackerearth: '',
          },
          communicationLevel: 'Intermediate',
          aptitudeLevel: 'Intermediate',
        },
        selfEvaluation: {
          academicStrengths: ['Exceptional spatial reasoning and 3D CAD modeling'],
          technicalStrengths: ['SolidWorks, ANSYS simulation, machine shop welding'],
          communicationStrengths: ['Honest, dedicated team player'],
          leadershipQualities: ['Vehicle fabrication captain for SAE college team'],
          teamworkAbilities: ['Works long hours in mechanical fabrication bay with peers'],
          improvementAreas: ['English fluency in corporate core interviews', 'Python scripting for simulation automation'],
          subjectsNeedSupport: [],
          techSkillsToDevelop: ['MATLAB Simulink for EV simulation', 'CATIA V5'],
          commSkillsToImprove: ['Group discussion confidence and spoken English'],
          aptitudeSkillsToImprove: ['Logical deduction and speed aptitude'],
          mentorSupportExpected: 'Guidance on core automotive campus recruitment training and scholarship options.',
          shortTermGoal: 'Clear campus technical assessment for Ashok Leyland / Hyundai / TVS Motors.',
          longTermGoal: 'Senior Mechanical Design Engineer in an Electric Vehicle OEM.',
        },
        careerGoal: {
          primaryGoal: 'Placement',
          placement: {
            preferredRole: 'Graduate Engineer Trainee (GET) - Mechanical / R&D',
            preferredDomain: 'Software Development',
            companyType: 'Core',
            expectedSalary: '₹6–9 LPA',
            preferredLocation: 'Chennai / Pune / Coimbatore',
            targetCompanies: ['Ashok Leyland', 'TVS Motor Company', 'Hyundai Motor India', 'Mahindra R&D', 'L&T'],
            trainingSupport: 'Core technical GD & HR interview mock sessions.',
            skillsToImprove: ['GD&T', 'Electric Vehicle Fundamentals'],
          },
        },
        mentorInterventions: [],
        consent: true,
      },

      // 8. IT Department - Entrepreneurship (SaaS / AI Product, Day Scholar)
      {
        personalDetails: {
          registerNumber: '710021205029',
          name: 'Pooja Lakshmanan',
          dob: '2003-12-18',
          gender: 'Female',
          department: 'IT',
          section: 'B',
          institutionalEmail: 'pooja.l21@college.edu',
          personalEmail: 'pooja.laksh.tech@gmail.com',
          mobile: '9840778899',
          residentialAddress: 'No. 7, 2nd Seaward Road, Valmiki Nagar, Thiruvanmiyur, Chennai',
          category: 'Day Scholar',
          hostelName: '',
          distanceFromCollege: 16,
        },
        familyDetails: {
          father: {
            name: 'Lakshmanan S',
            occupation: 'Pharmacist',
            incomeRange: '₹3–5 Lakhs',
            mobile: '9840778890',
          },
          mother: {
            name: 'Radha L',
            occupation: 'Nurse',
            incomeRange: '₹1–3 Lakhs',
            mobile: '9840778891',
          },
          guardianName: '',
          emergencyContact: '9840778890',
          firstGenGraduate: 'Yes',
          scholarshipReceived: 'No',
          guidanceRequired: 'Yes',
        },
        semesters: [
          {
            semesterNumber: 1,
            sgpa: 8.0,
            cgpa: 8.0,
            attendance: 90,
            arrearStatus: 'No',
            numberOfArrears: 0,
            academicAchievements: '',
            subjectsStrong: ['Python', 'Engineering Physics'],
          },
          {
            semesterNumber: 2,
            sgpa: 8.3,
            cgpa: 8.15,
            attendance: 91,
            arrearStatus: 'No',
            numberOfArrears: 0,
            academicAchievements: '',
            subjectsStrong: ['Object Oriented Programming'],
          },
          {
            semesterNumber: 3,
            sgpa: 8.5,
            cgpa: 8.27,
            attendance: 88,
            arrearStatus: 'No',
            numberOfArrears: 0,
            academicAchievements: 'Selected for NSRCEL IIM-Bangalore Women Startup Program',
            subjectsStrong: ['Software Engineering', 'Database Systems'],
          },
        ],
        arrears: [],
        technicalProfile: {
          programmingLanguages: ['TypeScript', 'Python', 'Dart'],
          technicalSkills: ['Next.js', 'Tailwind CSS', 'FastAPI', 'PostgreSQL', 'Flutter'],
          preferredDomain: 'Web Development',
          areasOfInterest: ['HealthTech SaaS', 'Mobile Apps', 'FinTech for Women'],
          certifications: [
            {
              name: 'Full Stack Open Certification',
              issuingOrg: 'University of Helsinki',
              completionDate: '2023-11-10',
              certificateLink: 'https://fullstackopen.com/certificate/pooja',
            },
          ],
          projects: [
            {
              title: 'MedSync: Automated Pill Reminder & Prescription Sync App',
              description: 'Elderly friendly medication adherence platform connecting pharmacies, family members, and elderly patients with WhatsApp reminder bots.',
              technologies: ['Flutter', 'FastAPI', 'Twilio WhatsApp API', 'PostgreSQL'],
              projectStatus: 'Completed',
              githubLink: 'https://github.com/pooja-l/medsync-app',
            },
          ],
          hackathons: [
            {
              name: 'Google Women Techmakers Hackathon 2023',
              date: '2023-09-08',
              achievement: '1st Prize - Regional Chapter',
            },
          ],
          codingContests: [],
          internships: [],
          profileLinks: {
            github: 'https://github.com/pooja-lakshmanan',
            linkedin: 'https://linkedin.com/in/pooja-lakshmanan-founder',
            hackerrank: 'https://hackerrank.com/pooja_it',
            hackerearth: '',
          },
          communicationLevel: 'Excellent',
          aptitudeLevel: 'Advanced',
        },
        selfEvaluation: {
          academicStrengths: ['Consistently high grades with balanced product development output'],
          technicalStrengths: ['Full-stack TypeScript, mobile UI/UX, product design'],
          communicationStrengths: ['Articulate product vision, comfortable speaking to mentors and users'],
          leadershipQualities: ['Founder of Women in Tech student circle in college'],
          teamworkAbilities: ['Agile sprint manager in student team'],
          improvementAreas: ['Understanding enterprise B2B sales cycles and contracts'],
          subjectsNeedSupport: [],
          techSkillsToDevelop: ['HIPAA compliance security', 'Docker microservices'],
          commSkillsToImprove: ['VC investor pitching and financial negotiation'],
          aptitudeSkillsToImprove: ['Business unit economics calculations'],
          mentorSupportExpected: 'Guidance on incubation grants, trademark registration, and legal mentorship for startups.',
          shortTermGoal: 'Launch beta version of MedSync across 5 local retirement communities in Chennai.',
          longTermGoal: 'Build MedSync into an established digital health companion serving 100,000+ senior citizens.',
        },
        careerGoal: {
          primaryGoal: 'Entrepreneurship',
          entrepreneurship: {
            startupIdea: 'MedSync Health Technologies: Digital Companion for Senior Citizen Medication Adherence',
            problemAddressed: 'Over 50% of chronic disease patients fail to take prescribed daily medications correctly, leading to preventable hospitalizations.',
            proposedSolution: 'AI-assisted WhatsApp and voice call interactive bot paired with smart QR code pill packaging that confirms doses without complex app navigation.',
            targetCustomers: 'Senior citizen households, assisted living communities, geriatric clinics.',
            currentStage: 'MVP',
            teamDetails: 'Pooja (Product/Tech), 1 UI/UX intern, 1 Medical advisor (Doctor from Sri Ramachandra Hospital).',
            techSupport: 'College cloud computing credit grant for AWS hosting.',
            fundingSupport: 'Applying for Startup India Seed Fund (SISFS) ₹10 Lakhs prototype grant.',
            incubationSupport: 'Mentorship on medical device regulations, data privacy, and hospital pilot agreements.',
            expectedLaunchYear: 2025,
          },
        },
        mentorInterventions: [
          {
            date: new Date('2024-02-14'),
            reason: 'Startup Incubator Recommendation Letter',
            mentorNote: 'Provided faculty endorsement letter for Pooja application to NSRCEL IIMB Women Startup cohort. Validated business logic and ethics compliance.',
            actionTaken: 'Signed faculty advisor agreement.',
            followUpDate: new Date('2024-07-10'),
            status: 'Resolved',
            mentorName: 'Prof. Priya Chandrasekar',
            mentorId: facultyUser._id,
          },
        ],
        consent: true,
      },
    ];

    studentsData.forEach((student) => { student.createdBy = adminUser._id; student.createdByRole = adminUser.role; student.updatedBy = adminUser._id; student.updatedByRole = adminUser.role; });
    const inserted = await Student.insertMany(studentsData);
    console.log(`[System] Successfully seeded ${inserted.length} students.`);

    await AuditLog.create({
      userId: adminUser._id,
      userName: adminUser.name,
      userRole: adminUser.role,
      action: 'SYSTEM_SEED',
      details: `Auto-initialized database with ${inserted.length} realistic student records and 2 user accounts.`,
    });
  } catch (err) {
    console.error('Seed helper error:', err.message);
  }
};

module.exports = { seedInitialData };
